import unittest
import unittestCases
from unittestSkip import MySkippedTestCase, MyTestCase
import unittestDistinguishTestIterations
from HtmlTestRunner_English import HTMLTestRunnerEnglish
from HTMLTestRunner_Chinese import HTMLTestRunnerChinese


def normal():
    suite = unittest.TestSuite()

    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(MySkippedTestCase))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(MyTestCase))
    # suite.addTests(unittest.TestLoader().loadTestsFromModule(unittestDistinguishTestIterations))
    # suite.addTests(unittest.TestLoader().loadTestsFromName("TestSequenceFunctions", unittestCases))
    # suite.addTests(unittest.TestLoader().loadTestsFromNames(["TestSequenceFunctions", "TestCaseClass"],unittestCases))

    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)


def write_to_file():
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(MyTestCase))
    with open('unittestTextReport.txt', 'a') as f:
        runner = unittest.TextTestRunner(stream=f, verbosity=2)
        runner.run(suite)


def display_html_report_english():
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(MyTestCase))
    with open('HTMLReportEnglish.html', 'w') as f:
        runner = HTMLTestRunnerEnglish(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)


def display_html_report_chinese():
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(MySkippedTestCase))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(MyTestCase))
    suite.addTests(unittest.TestLoader().loadTestsFromModule(unittestDistinguishTestIterations))
    suite.addTests(unittest.TestLoader().loadTestsFromName("TestSequenceFunctions", unittestCases))
    suite.addTests(unittest.TestLoader().loadTestsFromNames(["TestSequenceFunctions", "TestCaseClass"],unittestCases))
    with open('HTMLReportChinese.html', 'w') as f:
        runner = HTMLTestRunnerChinese(stream=f,
                                title='中文测试报告',
                                description='描述：来啦来啦来啦',
                                verbosity=2
                                )
        runner.run(suite)

if __name__ == '__main__':
    # normal()
    # write_to_file()
    # display_html_report_english()
    display_html_report_chinese()
